version: "3.7"
services:
   minio:
    image: 'bitnami/minio:2023.9.30'
    container_name:  minio
    restart: unless-stopped
    ports:
      - '${MINIO_PORT1:-9000}:9000'
      - '${MINIO_PORT2:-9001}:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - internal
networks:
  internal:
    external: false
    name: internal
volumes:
    minio_data:
        driver: local
    
  